name: API Cron Job

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch: # Allows manual trigger

jobs:
  hit-api:
    runs-on: ubuntu-latest
    steps:
      - name: Send API Request
        run: |
          curl -X GET "https://hr-email-tap-backend.onrender.com/"
